name: Starter workflow

on:
  workflow_dispatch:
    inputs:
      BUCKET_NAME:
        type: choice
        required: true
        options:
          - sadljd123
      # FOLDERS:
      #   type: string
      #   required: true
jobs:
  build-test-scan-wf:
   strategy:
      matrix:
        folders: ['envs', 'tests']
    uses: sparshbaurasi/terraform-cicd/.github/workflows/main.yml@main
    with:
      BUCKET_NAME: ${{ github.event.inputs.BUCKET_NAME }}
      FOLDERS: ${{ matrix.folders}}
    secrets:
      AWS_OIDC_ROLE: ${{ secrets.AWS_OIDC_ROLE_ARN }}
