name: Reusable workflow

on:
  workflow_dispatch:
    inputs:
      BUCKET_NAME:
        type: choice
        required: true
        options:
         - s3-composite-file-upload-action
      KEY_NAME:
        type: string
#       FILE_NAME:
#         type: string
#         required: true
#     secrets:
#       AWS_ACCESS_KEY:
#         required: true
#       AWS_SECRET_ACCESS_KEY:
#         required: true
jobs:
  build:
    strategy:
      matrix:
        folders: [tests,envs]
    runs-on: ubuntu-20.04
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::612490972332:role/Idp-role-for-github
          role-session-name: Idp-role-for-github
          aws-region: ap-south-1
      - name: Copy to s3
        uses: sparshbaurasi/terraform-cicd/S3-file-update@main
        with:
          BUCKET_NAME: ${{ github.event.inputs.BUCKET_NAME }}
          KEY_NAME: ${{ github.event.inputs.KEY_NAME }}
          FILE_NAME: ${{ matrix.folders }}
