name: Starter workflow

on:
  workflow_dispatch:
    inputs:
      BUCKET_NAME:
        type: choice
        required: true
        options:
          - test-bucket-dlq
      FOLDERS:
#         type: string
        default: [test]
jobs:
  build-test-scan-wf:
    uses: sparshbaurasi/terraform-cicd/.github/workflows/main.yml@main
    with:
      BUCKET_NAME: ${{ github.event.inputs.BUCKET_NAME }}
      FOLDERS: ${{ github.event.inputs.FOLDERS }}
    secrets:
      AWS_OIDC_ROLE: ${{ secrets.AWS_OIDC_ROLE_ARN }}
